package simulator.von.neumann;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JTextField;

/**
 *
 * @author cacar
 */
public class principal extends javax.swing.JFrame implements Runnable {

    int x = 220, y = 55;
    Thread hilo;
    int velocidad = 20;

    public principal() {
        this.setLocation(300, 25);
        initComponents();
        hilo = new Thread(this);
        restriccion();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnPlay = new javax.swing.JButton();
        btnPausar = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtDecodificador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtInstrucciones = new javax.swing.JTextField();
        txtContProgr = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_memoria = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtDatos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtEntrada = new javax.swing.JTextField();
        txtAcumulador = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        btnPlay.setText("PLAY");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnPausar.setText("PAUSAR");
        btnPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausarActionPerformed(evt);
            }
        });

        btnReiniciar.setText("REINICIAR");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPausar)
                .addGap(18, 18, 18)
                .addComponent(btnReiniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnReiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                    .addComponent(btnPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPausar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        jLabel1.setText("UNIDAD DE CONTROL");

        txtInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInstruccionesActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel8.setText("Decodificador");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel9.setText("Cont. Programa");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setText("R. Instrucciones");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtContProgr, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel10)
                                        .addGap(1, 1, 1)))
                                .addGap(4, 4, 4)))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDecodificador, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(txtDecodificador, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txtContProgr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));

        tabla_memoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0000", "00000100"},
                {"0001", "00000101"},
                {"0010", "01100111"},
                {"0011", "01110000"},
                {"0100", "00000101"},
                {"0101", "00001011"},
                {"0110", "00000000"},
                {"0111", "00000000"}
            },
            new String [] {
                "Dir.", "Contenido"
            }
        ));
        jScrollPane1.setViewportView(tabla_memoria);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setText("R. Direcciones");

        txtDireccion.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setText("Tabla de Memoria");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setText("R. Datos");

        jLabel2.setText("MEMORIA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(16, 16, 16)))
                .addGap(38, 38, 38))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));

        txtEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaActionPerformed(evt);
            }
        });

        txtAcumulador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAcumuladorActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setText("R.entrada");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setText("Acumulador");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 87, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(70, 70, 70))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtAcumulador, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAcumulador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed

        txtContProgr.setText("0000");
        txtInstrucciones.setText("00000000");
        iniciar();

    }//GEN-LAST:event_btnPlayActionPerformed

    public void iniciar() {
        hilo.start();
    }
    private void txtAcumuladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAcumuladorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAcumuladorActionPerformed

    private void txtInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstruccionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstruccionesActionPerformed

    private void txtEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaActionPerformed

    private void btnPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausarActionPerformed
        hilo.stop();
    }//GEN-LAST:event_btnPausarActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        hilo.suspend();
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed
    @Override
    public void paint(Graphics g) {
        super.paint(g);

        g.drawLine(50, 80, 80, 80);//eje horizontal
        g.drawLine(130, 120, 80, 120);//segunda linea horizontal
        g.drawLine(210, 120, 380, 120);//tercera linea horizontal
        g.drawLine(380, 60, 530, 60);//cuarta linea horizontal
        g.drawLine(210, 63, 230, 63);//cuarta linea horizontal
        g.drawLine(130, 63, 100, 63);//quinta linea horizontal
        g.drawLine(230, 40, 100, 40);//sexta linea horizontal
        g.drawLine(230, 180, 80, 180);//septima linea horizontal
        g.drawLine(155, 282, 80, 282);//octava linea horizontal

        g.drawLine(200, 340, 250, 340);//novena linea horizontal1
        g.drawLine(200, 358, 250, 358);//novena linea horizontal2
        g.drawLine(200, 375, 250, 375);//novena linea horizontal3
        g.drawLine(200, 390, 250, 390);//novena linea horizontal4
        g.drawLine(200, 405, 250, 405);//novena linea horizontal5
        g.drawLine(200, 420, 250, 420);//novena linea horizontal6
        g.drawLine(200, 435, 250, 435);//novena linea horizontal7
        g.drawLine(200, 450, 250, 450);//novena linea horizontal8

        g.drawLine(406, 340, 470, 340);//novena linea horizontal1
        g.drawLine(406, 358, 470, 358);//novena linea horizontal2
        g.drawLine(406, 375, 470, 375);//novena linea horizontal3
        g.drawLine(406, 390, 470, 390);//novena linea horizontal4
        g.drawLine(406, 405, 470, 405);//novena linea horizontal5
        g.drawLine(406, 420, 470, 420);//novena linea horizontal6
        g.drawLine(406, 435, 470, 435);//novena linea horizontal7
        g.drawLine(406, 450, 470, 450);//novena linea horizontal8

        g.drawLine(480, 295, 600, 295);//novena linea horizontal1
        g.drawLine(510, 120, 550, 120);//novena linea horizontal
        g.drawLine(380, 290, 430, 290);//novena linea horizontal
        g.drawLine(380, 190, 430, 190);//novena linea horizontal
        g.drawLine(80, 80, 80, 282);//eje vertical1
        g.drawLine(100, 40, 100, 63);//eje vertical2
        g.drawLine(230, 40, 230, 180);//eje vertical3
        g.drawLine(200, 300, 200, 450);//eje vertical4
        g.drawLine(470, 300, 470, 450);//eje vertical4
        g.drawLine(600, 190, 600, 295);//eje vertical1
        g.drawLine(380, 60, 380, 290);//eje vertical1
        g.drawLine(530, 60, 530, 120);//eje vertical4
        //bola
        g.setColor(Color.red);
        g.fillOval(x, y, 20, 20);// punto inicial

    }

    //metodo para ejecutar  bola
    public void run() {
        try {
            while (true) {
                /*primera etapa*/
                while (y < getHeight() - 20) {
                    Thread.sleep(velocidad);
                    y += 5;
                    repaint();
                    if (y == 170) {
                        while (x > 10) {
                            Thread.sleep(velocidad);
                            x -= 5;
                            repaint();
                            if (x == 70) {
                                /*segunda etapa*/
                                while (y < getHeight() - 20) {
                                    Thread.sleep(velocidad);
                                    y += 5;
                                    repaint();
                                    if (y == 270) {
                                        while (x > 10) {
                                            Thread.sleep(velocidad);
                                            x += 5;
                                            repaint();
                                            if (x == 115) {
                                                txtDireccion.setHorizontalAlignment(JTextField.CENTER);
                                                txtDireccion.setBackground(Color.CYAN);
                                                txtDireccion.setText("0000");
                                                txtContProgr.setHorizontalAlignment(JTextField.CENTER);
                                                txtContProgr.setBackground(Color.MAGENTA);
                                                txtContProgr.setText("0001");
                                                Thread.sleep(velocidad);
                                                while (x > 10) {
                                                    Thread.sleep(velocidad);
                                                    x = 190;
                                                    y += 5;
                                                    repaint();
                                                    if (y == 330) {
                                                        while (x > 10) {
                                                            Thread.sleep(velocidad);
                                                            x += 5;
                                                            repaint();
                                                            if (x == 460) {
                                                                while (y < getHeight() - 20) {
                                                                    Thread.sleep(velocidad);
                                                                    y -= 5;
                                                                    repaint();
                                                                    if (y == 275) {
                                                                        txtDatos.setHorizontalAlignment(JTextField.CENTER);
                                                                        txtDatos.setBackground(Color.CYAN);
                                                                        txtDatos.setText("00000100");
                                                                        while (x > 10) {
                                                                            Thread.sleep(velocidad);
                                                                            x -= 5;
                                                                            repaint();
                                                                            if (x == 370) {
                                                                                while (y < getHeight() - 20) {
                                                                                    Thread.sleep(velocidad);
                                                                                    y -= 5;
                                                                                    repaint();
                                                                                    if (y == 110) {
                                                                                        while (x > 10) {
                                                                                            Thread.sleep(velocidad);
                                                                                            x -= 5;
                                                                                            repaint();
                                                                                            if (x == 200) {
                                                                                                txtInstrucciones.setHorizontalAlignment(JTextField.CENTER);
                                                                                                txtInstrucciones.setBackground(Color.CYAN);
                                                                                                txtInstrucciones.setText("00000100");
                                                                                            }
                                                                                            if (x == 70) {
                                                                                                while (y < getHeight() - 20) {
                                                                                                    Thread.sleep(velocidad);
                                                                                                    y -= 5;
                                                                                                    repaint();
                                                                                                    if (y == 70) {
                                                                                                        while (x > 10) {
                                                                                                            Thread.sleep(velocidad);
                                                                                                            x -= 5;
                                                                                                            repaint();
                                                                                                            if (x == 50) {
                                                                                                                txtDecodificador.setHorizontalAlignment(JTextField.CENTER);
                                                                                                                txtDecodificador.setBackground(Color.CYAN);
                                                                                                                txtDecodificador.setText("+");
                                                                                                                while (x > 10) {
                                                                                                                    Thread.sleep(velocidad);
                                                                                                                    x += 5;
                                                                                                                    repaint();
                                                                                                                    if (x == 70) {

                                                                                                                        while (y < getHeight() - 20) {
                                                                                                                            Thread.sleep(velocidad);
                                                                                                                            y += 5;
                                                                                                                            repaint();
                                                                                                                            if (y == 270) {
                                                                                                                                while (x > 10) {
                                                                                                                                    Thread.sleep(velocidad);
                                                                                                                                    x += 5;
                                                                                                                                    repaint();
                                                                                                                                    if (x == 120) {
                                                                                                                                        txtDireccion.setHorizontalAlignment(JTextField.CENTER);
                                                                                                                                        txtDireccion.setBackground(Color.MAGENTA);
                                                                                                                                        txtDireccion.setText("0100");
                                                                                                                                    }
                                                                                                                                    if (x == 190) {
                                                                                                                                        while (x > 10) {
                                                                                                                                            Thread.sleep(velocidad);
                                                                                                                                            y += 5;
                                                                                                                                            repaint();
                                                                                                                                            if (y == 395) {
                                                                                                                                                while (x > 10) {
                                                                                                                                                    Thread.sleep(velocidad);
                                                                                                                                                    x += 5;
                                                                                                                                                    repaint();
                                                                                                                                                    if (x == 460) {
                                                                                                                                                        while (x > 10) {
                                                                                                                                                            Thread.sleep(velocidad);
                                                                                                                                                            y -= 5;
                                                                                                                                                            repaint();
                                                                                                                                                            if (y == 290) {
                                                                                                                                                                txtDatos.setHorizontalAlignment(JTextField.CENTER);
                                                                                                                                                                txtDatos.setBackground(Color.MAGENTA);
                                                                                                                                                                txtDatos.setText("00000101");
                                                                                                                                                                while (x > 10) {
                                                                                                                                                                    Thread.sleep(velocidad);
                                                                                                                                                                    x += 5;
                                                                                                                                                                    repaint();
                                                                                                                                                                    if (x == 590) {
                                                                                                                                                                        while (x > 10) {
                                                                                                                                                                            Thread.sleep(velocidad);
                                                                                                                                                                            y -= 5;
                                                                                                                                                                            repaint();
                                                                                                                                                                            if (y == 200) {
                                                                                                                                                                                txtEntrada.setHorizontalAlignment(JTextField.CENTER);
                                                                                                                                                                                txtEntrada.setBackground(Color.MAGENTA);
                                                                                                                                                                                txtEntrada.setText("00000101");

                                                                                                                                                                                while (x > 10) {
                                                                                                                                                                                    Thread.sleep(velocidad);
                                                                                                                                                                                    y = 110;
                                                                                                                                                                                    x -= 5;
                                                                                                                                                                                    repaint();
                                                                                                                                                                                    if (x == 520) {
                                                                                                                                                                                        while (x > 10) {
                                                                                                                                                                                            Thread.sleep(velocidad);
                                                                                                                                                                                            y -= 5;
                                                                                                                                                                                            repaint();
                                                                                                                                                                                            if (y == 50) {
                                                                                                                                                                                                while (x > 10) {
                                                                                                                                                                                                    Thread.sleep(velocidad);
                                                                                                                                                                                                    x -= 5;
                                                                                                                                                                                                    repaint();
                                                                                                                                                                                                    if (x == 370) {
                                                                                                                                                                                                        while (x > 10) {
                                                                                                                                                                                                            Thread.sleep(velocidad);
                                                                                                                                                                                                            y += 5;
                                                                                                                                                                                                            repaint();
                                                                                                                                                                                                            if (y == 180) {
                                                                                                                                                                                                                while (x > 10) {
                                                                                                                                                                                                                    Thread.sleep(velocidad);
                                                                                                                                                                                                                    x += 5;
                                                                                                                                                                                                                    repaint();
                                                                                                                                                                                                                    if (x == 410) {
                                                                                                                                                                                                                        txtAcumulador.setHorizontalAlignment(JTextField.CENTER);
                                                                                                                                                                                                                        txtAcumulador.setBackground(Color.MAGENTA);
                                                                                                                                                                                                                        txtAcumulador.setText("00000101");
                                                                                                                                                                                                                        while (x > 10) {
                                                                                                                                                                                                                            Thread.sleep(velocidad);
                                                                                                                                                                                                                            x -= 5;
                                                                                                                                                                                                                            repaint();
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                }
                                                                                                                                                                                                            }
                                                                                                                                                                                                        }
                                                                                                                                                                                                    }
                                                                                                                                                                                                }
                                                                                                                                                                                            }
                                                                                                                                                                                        }
                                                                                                                                                                                    }
                                                                                                                                                                                }
                                                                                                                                                                            }
                                                                                                                                                                        }
                                                                                                                                                                    }
                                                                                                                                                                }
                                                                                                                                                            }
                                                                                                                                                        }
                                                                                                                                                    }
                                                                                                                                                }
                                                                                                                                            }
                                                                                                                                        }
                                                                                                                                    }

                                                                                                                                }
                                                                                                                            }
                                                                                                                        }
                                                                                                                    }
                                                                                                                }
                                                                                                            }
                                                                                                        }
                                                                                                    }
                                                                                                }
                                                                                            }
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }

                                                            }
                                                        }
                                                    }
                                                }
                                                //hilo.destroy();
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }/**/

            }
        } catch (Exception e) {
            System.out.printf("error ", e);
        }
    }

    public void restriccion() {
        txtContProgr.setEditable(false);
        txtDatos.setEditable(false);
        txtDecodificador.setEditable(false);
        txtDireccion.setEditable(false);
        txtInstrucciones.setEditable(false);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPausar;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_memoria;
    private javax.swing.JTextField txtAcumulador;
    private javax.swing.JTextField txtContProgr;
    private javax.swing.JTextField txtDatos;
    private javax.swing.JTextField txtDecodificador;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEntrada;
    private javax.swing.JTextField txtInstrucciones;
    // End of variables declaration//GEN-END:variables
}
